
import type { GeneratedConfig } from '../types';

type MockExplanation = {
  vi: string;
  en: string;
}

// A template for a generated config. The final values will be computed.
interface MockConfigTemplate {
  explanation: MockExplanation;
  files: {
    fileName: string;
    fileContent: string;
  }[];
  recommendedRamGB: number;
  recommendedCpu: string;
  recommendedSsdGB: number;
  defaultWorldName: string;
}

// Using a Record for strong typing. Keys should be lowercase game names.
export const MOCK_GAME_DATA: Record<string, MockConfigTemplate> = {
  'minecraft': {
    explanation: {
      vi: `Đây là hướng dẫn chi tiết để thiết lập máy chủ **Minecraft** của bạn:\n\n**1. Chuẩn bị:**\n   - Đảm bảo bạn đã cài đặt **Java 17** trở lên.\n   - Tải tệp \`server.jar\` từ trang chủ chính thức của Minecraft.\n\n**2. Tạo thư mục máy chủ:**\n   - Tạo một thư mục mới, trống cho máy chủ của bạn (ví dụ: \`minecraft-server\`).\n\n**3. Tải về và Sắp xếp tệp:**\n   - Tải các tệp đã tạo (\`server.properties\`, \`start.sh\`, \`eula.txt\`) và đặt chúng vào thư mục \`minecraft-server\` cùng với tệp \`server.jar\`.\n\n**4. Cấp quyền (Linux/macOS):**\n   - Mở terminal, điều hướng đến thư mục máy chủ và chạy lệnh sau:\n   \`\`\`\n   chmod +x start.sh\n   \`\`\`\n\n**5. Khởi động máy chủ:**\n   - Chạy lệnh sau trong terminal:\n   \`\`\`\n   ./start.sh\n   \`\`\`\n   - Lần khởi động đầu tiên sẽ mất một lúc để tạo thế giới. Máy chủ của bạn hiện đã hoạt động!`,
      en: `Here is a detailed guide to set up your **Minecraft** server:\n\n**1. Prerequisites:**\n   - Make sure you have **Java 17** or newer installed.\n   - Download the \`server.jar\` file from the official Minecraft website.\n\n**2. Create Server Folder:**\n   - Create a new, empty folder for your server (e.g., \`minecraft-server\`).\n\n**3. Download & Place Files:**\n   - Download the generated files (\`server.properties\`, \`start.sh\`, \`eula.txt\`) and place them inside the \`minecraft-server\` folder, alongside your \`server.jar\` file.\n\n**4. Make Executable (Linux/macOS):**\n   - Open your terminal, navigate to the server folder, and run the command:\n   \`\`\`\n   chmod +x start.sh\n   \`\`\`\n\n**5. Launch the Server:**\n   - Run the following command in your terminal:\n   \`\`\`\n   ./start.sh\n   \`\`\`\n   - The first launch will take a moment to generate the world. Your server is now live!`,
    },
    files: [
      {
        fileName: 'server.properties',
        fileContent: `
#Minecraft server properties
#Generated by AI Server Builder
motd={{serverName}}
server-port={{serverPort}}
max-players={{playerCount}}
level-seed={{worldSeedOrMap}}
gamemode={{minecraft_gamemode}}
difficulty={{minecraft_difficulty}}
pvp={{minecraft_pvp}}
online-mode={{minecraft_online_mode}}
enforce-whitelist={{minecraft_enforce_whitelist}}
view-distance=10
`
      },
      {
        fileName: 'start.sh',
        fileContent: `
#!/bin/bash
# A simple startup script for a Minecraft Server
# Make sure to have 'server.jar' in the same directory.

echo "Starting Minecraft server '{{serverName}}'..."
java -Xmx{{recommendedRamGB}}G -Xms1G -jar server.jar nogui
`
      },
      {
        fileName: 'eula.txt',
        fileContent: `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).\neula=true`
      }
    ],
    recommendedRamGB: 6,
    recommendedCpu: "4+ Cores @ 3.2GHz+",
    recommendedSsdGB: 20,
    defaultWorldName: 'world',
  },
  'discord bot': {
    explanation: {
        vi: `Bot Discord của bạn giờ đây là một **trình tạo tệp máy chủ** tương tác!\n\n**1. Cổng thông tin nhà phát triển Discord:**\n   - Tới Discord Developer Portal, tạo một Ứng dụng mới, thêm một Bot và sao chép **Token** của nó.\n   - **QUAN TRỌNG:** Giữ token này bí mật!\n\n**2. Thiết lập dự án:**\n   - Tải về tất cả các tệp đã tạo.\n   - Mở tệp \`.env\` và dán token bot và ID client của bạn.\n   - Trong terminal, chạy \`npm install\` để cài đặt các gói phụ thuộc (bạn cần Node.js).\n\n**3. Mời Bot:**\n   - Trong Developer Portal, đi đến 'OAuth2' -> 'URL Generator'.\n   - Chọn các phạm vi \`bot\` và \`applications.commands\`.\n   - Mời bot vào máy chủ của bạn bằng URL đã tạo.\n\n**4. Đăng ký lệnh:**\n   - Trong terminal, chạy \`npm run deploy-commands\` để đăng ký các lệnh slash mới, bao gồm lệnh \`/generate\` mạnh mẽ.\n\n**5. Chạy Bot & Tạo tệp:**\n   - Chạy \`npm start\` để đưa bot của bạn lên mạng.\n   - Trong bất kỳ kênh nào mà bot của bạn có thể thấy, hãy gõ \`/generate\` và điền các tùy chọn. Bot sẽ tạo và gửi các tệp máy chủ trực tiếp cho bạn!`,
        en: `Your Discord Bot is now an interactive **server file generator**!\n\n**1. Discord Developer Portal:**\n   - Go to the Discord Developer Portal, create a new Application, add a Bot, and copy its **Token**.\n   - **IMPORTANT:** Keep this token secret!\n\n**2. Setup Project:**\n   - Download all the generated files.\n   - Open the \`.env\` file and paste your bot token and client ID.\n   - In your terminal, run \`npm install\` to install dependencies (you need Node.js).\n\n**3. Invite Bot:**\n   - In the Developer Portal, go to 'OAuth2' -> 'URL Generator'.\n   - Select the \`bot\` and \`applications.commands\` scopes.\n   - Invite the bot to your server using the generated URL.\n\n**4. Register Commands:**\n   - In your terminal, run \`npm run deploy-commands\` to register the new slash commands, including the powerful \`/generate\` command.\n\n**5. Run Bot & Generate:**\n   - Run \`npm start\` to bring your bot online.\n   - In any channel your bot can see, type \`/generate\` and fill in the options. The bot will create and send the server files right back to you!`,
    },
    files: [
        {
            fileName: 'package.json',
            fileContent: `
{
    "name": "{{serverNameSlug}}",
    "version": "1.0.0",
    "description": "A Discord bot that generates game server files, created by AI Server Builder.",
    "main": "index.js",
    "scripts": {
        "start": "node index.js",
        "deploy-commands": "node deploy-commands.js"
    },
    "dependencies": {
        "discord.js": "^14.15.3",
        "dotenv": "^16.4.5"
    }
}
`
        },
        {
            fileName: 'index.js',
            fileContent: `
const { Client, Events, GatewayIntentBits, Collection, AttachmentBuilder } = require('discord.js');
const { generateFiles } = require('./generator');
require('dotenv').config();

// Create a new client instance
const client = new Client({ intents: [GatewayIntentBits.Guilds] });

client.commands = new Collection();
        
const pingCommand = {
    name: 'ping',
    description: 'Replies with Pong!',
    execute: async (interaction) => {
        await interaction.reply('Pong!');
    },
};

const generateCommand = {
    name: 'generate',
    description: 'Generates server files for a specific game.',
    // Command options are defined in deploy-commands.js
    execute: async (interaction) => {
        await interaction.deferReply();
        try {
            const config = {
                gameName: interaction.options.getString('game'),
                serverName: interaction.options.getString('server-name'),
                playerCount: interaction.options.getInteger('player-count') ?? 10,
                serverPort: interaction.options.getInteger('port') ?? 25565,
                serverDescription: interaction.options.getString('description') ?? 'A server generated by {{serverName}}.',
                worldSeedOrMap: interaction.options.getString('seed') ?? '',
                advancedOptions: {}, // Advanced options are not supported via slash command for simplicity
            };

            const result = generateFiles(config);

            if (!result || !result.files || result.files.length === 0) {
                await interaction.editReply({ content: \`Could not generate files for **\${config.gameName}**. Please check the game name.\`, ephemeral: true });
                return;
            }

            const attachments = result.files.map(file => {
                return new AttachmentBuilder(Buffer.from(file.fileContent, 'utf-8'), { name: file.fileName });
            });

            await interaction.editReply({
                content: \`Here are your generated server files for **\${config.gameName}**! \n\n> \${result.explanation.split('\\n')[0]}\`,
                files: attachments
            });

        } catch (error) {
            console.error('Error during file generation command:', error);
            await interaction.editReply({ content: 'An unexpected error occurred while generating the files. Please check the console.', ephemeral: true });
        }
    }
};

client.commands.set(pingCommand.name, pingCommand);
client.commands.set(generateCommand.name, generateCommand);

client.once(Events.ClientReady, c => {
    console.log(\`Ready! Logged in as \${c.user.tag}\`);
    c.user.setActivity('{{serverDescription}}');
});

client.on(Events.InteractionCreate, async interaction => {
    if (!interaction.isChatInputCommand()) return;

    const command = client.commands.get(interaction.commandName);
    if (!command) return;

    try {
        await command.execute(interaction);
    } catch (error) {
        console.error(error);
        const replyOptions = { content: 'There was an error while executing this command!', ephemeral: true };
        if (interaction.replied || interaction.deferred) {
            await interaction.followUp(replyOptions);
        } else {
            await interaction.reply(replyOptions);
        }
    }
});

client.login(process.env.DISCORD_BOT_TOKEN);
`
        },
        {
            fileName: 'deploy-commands.js',
            fileContent: `
const { REST, Routes, ApplicationCommandOptionType } = require('discord.js');
const { SUPPORTED_GAMES_FOR_BOT } = require('./config.js');
require('dotenv').config();

const gameChoices = SUPPORTED_GAMES_FOR_BOT.map(game => ({ name: game, value: game }));

const commands = [
    {
        name: 'ping',
        description: 'Replies with Pong!',
    },
    {
        name: 'generate',
        description: 'Generates server files for a game.',
        options: [
            {
                name: 'game',
                description: 'The game to generate server files for.',
                type: ApplicationCommandOptionType.String,
                required: true,
                choices: gameChoices,
            },
            {
                name: 'server-name',
                description: 'The name of your server.',
                type: ApplicationCommandOptionType.String,
                required: true,
            },
            {
                name: 'player-count',
                description: 'The maximum number of players.',
                type: ApplicationCommandOptionType.Integer,
                required: false,
                minValue: 1,
                maxValue: 200,
            },
            {
                name: 'port',
                description: 'The server port.',
                type: ApplicationCommandOptionType.Integer,
                required: false,
                minValue: 1024,
                maxValue: 65535,
            },
            {
                name: 'description',
                description: 'A short description for your server.',
                type: ApplicationCommandOptionType.String,
                required: false,
            },
            {
                name: 'seed',
                description: 'The world seed or map name.',
                type: ApplicationCommandOptionType.String,
                required: false,
            },
        ]
    }
];

const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_BOT_TOKEN);

(async () => {
    try {
        if (!process.env.CLIENT_ID || process.env.CLIENT_ID === 'YOUR_CLIENT_ID_HERE') {
            throw new Error('CLIENT_ID is not set in the .env file. Please add it to register commands.');
        }
        console.log(\`Started refreshing \${commands.length} application (/) commands.\`);

        const data = await rest.put(
            Routes.applicationCommands(process.env.CLIENT_ID),
            { body: commands },
        );

        console.log(\`Successfully reloaded \${data.length} application (/) commands.\`);
    } catch (error) {
        console.error('\\n❌ An error occurred while deploying commands:');
        if (error && error.message.includes("Unknown Application")) { // More robust check
            console.error('Error: "Unknown Application". This means the CLIENT_ID in your .env file is incorrect.');
            console.error('➡️ Please double-check that you have copied the correct "Application ID" from the "General Information" page of your bot in the Discord Developer Portal and pasted it into the .env file.\\n');
        } else {
             console.error(error);
        }
    }
})();
`
        },
        {
          fileName: 'config.js',
          fileContent: `
// This file exports the list of games the bot can generate files for.
// "Discord Bot" is excluded to prevent recursion.
const SUPPORTED_GAMES_FOR_BOT = [
  'Minecraft',
  'Valheim',
  'Counter-Strike 2',
  'ARK: Survival Evolved',
  'Terraria',
  'Left 4 Dead 2',
  'Palworld',
  'Factorio',
  'Project Zomboid',
  "Don't Starve Together",
];

module.exports = { SUPPORTED_GAMES_FOR_BOT };
`
        },
        {
          fileName: 'generator.js',
          fileContent: `
// This file contains the core logic for generating server files.
const BOT_MOCK_GAME_DATA = {
  'minecraft': {
    explanation: "Here are your Minecraft server files. You will also need to download the official server.jar file to run it.",
    files: [
      {
        fileName: 'server.properties',
        fileContent: \`#Minecraft server properties\\n#Generated by {{serverName}}\\nmotd={{serverName}}\\nserver-port={{serverPort}}\\nmax-players={{playerCount}}\\nlevel-seed={{worldSeedOrMap}}\\ngamemode=survival\\ndifficulty=easy\\npvp=true\\nonline-mode=true\\nenforce-whitelist=false\\nview-distance=10\`
      },
      {
        fileName: 'start.sh',
        fileContent: \`#!/bin/bash\\necho \\"Starting Minecraft server '{{serverName}}'...\\"\\njava -Xmx{{recommendedRamGB}}G -Xms1G -jar server.jar nogui\`
      },
      {
        fileName: 'eula.txt',
        fileContent: \`#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).\\neula=true\`
      }
    ],
    recommendedRamGB: 6,
    recommendedCpu: "4+ Cores @ 3.2GHz+",
    recommendedSsdGB: 20,
    defaultWorldName: 'world',
  },
  'valheim': {
    explanation: "Here is the startup script for your Valheim server. Place it in your Valheim Dedicated Server directory.",
    files: [
      {
        fileName: 'start_server.sh',
        fileContent: \`#!/bin/bash\\nexport templdpath=\\\`dirname \\$0\\\`\\nexport LD_LIBRARY_PATH=\\$templdpath/linux64:\\$LD_LIBRARY_PATH\\nexport SteamAppId=892970\\necho \\"Starting Valheim server '{{serverName}}'...\\"\\n./valheim_server.x86_64 -nographics -batchmode -name \\"{{serverName}}\\" -port {{serverPort}} -world \\"{{worldSeedOrMap}}\\" -password \\"secret\\" -public 1\\necho \\"Valheim server stopped.\\"\`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "4+ Cores @ 3.0GHz+",
    recommendedSsdGB: 10,
    defaultWorldName: 'MyWorld',
  },
    'counter-strike 2': {
    explanation: "Here are the files for your Counter-Strike 2 server. Place start.sh in the root and the .cfg file in the csgo/cfg/ folder.",
    files: [
      {
        fileName: 'start.sh',
        fileContent: \`#!/bin/bash\\necho \\"Starting CS2 server '{{serverName}}'...\\"\\n./cs2 -dedicated +game_type 0 +game_mode 0 +map de_dust2 +sv_lan 0 +hostname \\"{{serverName}}\\" +port {{serverPort}}\`
      },
      {
        fileName: 'csgo/cfg/gamemode_casual.cfg',
        fileContent: \`hostname \\"{{serverName}}\\"\\nsv_cheats 0\\nmp_maxplayers {{playerCount}}\\nmp_autoteambalance 1\\nmp_limitteams 1\\nmp_roundtime 2.5\\nmp_freezetime 10\\necho \\"Casual server config loaded for '{{serverName}}'.\\"\`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 3.4GHz+",
    recommendedSsdGB: 40,
    defaultWorldName: 'de_dust2',
  },
  'ark: survival evolved': {
    explanation: "Here is the startup script for your ARK: Survival Evolved server. Place it in .../ShooterGame/Binaries/Linux/.",
    files: [
      {
        fileName: 'start.sh',
        fileContent: \`#!/bin/bash\\necho \\"Starting ARK server '{{serverName}}'...\\"\\n./ShooterGameServer {{worldSeedOrMap}}?listen?SessionName=\\"{{serverName}}\\"?MaxPlayers={{playerCount}}?QueryPort=27015?Port={{serverPort}} -server -log\`
      }
    ],
    recommendedRamGB: 8,
    recommendedCpu: "4+ Cores @ 3.4GHz+",
    recommendedSsdGB: 40,
    defaultWorldName: 'TheIsland',
  },
  'terraria': {
    explanation: "Here are the files for your Terraria server. Place them in your server directory.",
    files: [
      {
        fileName: 'serverconfig.txt',
        fileContent: \`worldname={{worldSeedOrMap}}\\nworldpath=Worlds\\nmaxplayers={{playerCount}}\\nport={{serverPort}}\\nmotd={{serverName}}\\nworldsize=2\\ndifficulty=0\`
      },
      {
        fileName: 'start.sh',
        fileContent: \`#!/bin/bash\\necho \\"Starting Terraria server...\\"\\n./TerrariaServer.bin.x86_64 -config serverconfig.txt\`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 2.8GHz+",
    recommendedSsdGB: 5,
    defaultWorldName: 'MyTerrariaWorld',
  },
  'left 4 dead 2': {
    explanation: "Here are the files for your Left 4 Dead 2 server. Place start.sh in the root and server.cfg in the left4dead2/cfg/ folder.",
    files: [
      {
        fileName: 'start.sh',
        fileContent: \`#!/bin/bash\\n./srcds_run -game left4dead2 +exec server.cfg +map c1m1_hotel +port {{serverPort}}\`
      },
      {
        fileName: 'left4dead2/cfg/server.cfg',
        fileContent: \`hostname \\"{{serverName}}\\"\\nsv_maxplayers {{playerCount}}\\nsv_cheats 0\\nsv_lan 0\`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 3.0GHz+",
    recommendedSsdGB: 15,
    defaultWorldName: 'c1m1_hotel',
  },
  'palworld': {
    explanation: "Here is the startup script for your Palworld server. Note: Server name and other settings must be configured in PalWorldSettings.ini after first launch.",
    files: [
      {
        fileName: 'start.sh',
        fileContent: \`#!/bin/bash\\necho \\"Starting Palworld Server...\\"\\n./PalServer.sh -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS\`
      }
    ],
    recommendedRamGB: 8,
    recommendedCpu: "4+ Cores @ 3.5GHz+",
    recommendedSsdGB: 30,
    defaultWorldName: 'Default',
  },
  'factorio': {
    explanation: "Here are the files for your Factorio server. Remember to create the save file first.",
    files: [
      {
        fileName: 'start.sh',
        fileContent: \`#!/bin/bash\\n./bin/x64/factorio --start-server {{worldSeedOrMap}}.zip --server-settings ./server-settings.json --port {{serverPort}}\`
      },
      {
        fileName: 'server-settings.json',
        fileContent: \`{\\n  \\"name\\": \\"{{serverName}}\\",\\n  \\"description\\": \\"{{serverDescription}}\\",\\n  \\"max_players\\": {{playerCount}},\\n  \\"visibility\\": { \\"public\\": true },\\n  \\"game_password\\": \\"\\",\\n  \\"auto_pause\\": true\\n}\`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 3.0GHz+",
    recommendedSsdGB: 5,
    defaultWorldName: 'factorio-save',
  },
  'project zomboid': {
    explanation: "Here is the startup script for your Project Zomboid server. Other settings are in the .ini files.",
    files: [
      {
        fileName: 'start-server.sh',
        fileContent: \`#!/bin/bash\\nDIR=\\"$( cd \\"$( dirname \\"\\\${BASH_SOURCE[0]}\\" )\\" >/dev/null 2>&1 && pwd )\\"\\n\\"\\$DIR/jre64/bin/java\\" -Xmx{{recommendedRamGB}}g -jar \\"\\$DIR/server.jar\\" -servername \\"{{serverName}}\\"\`
      }
    ],
    recommendedRamGB: 6,
    recommendedCpu: "4+ Cores @ 3.0GHz+",
    recommendedSsdGB: 15,
    defaultWorldName: 'Muldraugh, KY',
  },
  "don't starve together": {
    explanation: "Here are config files for your Don't Starve Together server. This setup is complex and requires manual steps like getting a cluster token.",
    files: [
      {
        fileName: 'cluster.ini',
        fileContent: \`[GAMEPLAY]\\ngame_mode = survival\\nmax_players = {{playerCount}}\\npvp = false\\npause_when_empty = true\\n[NETWORK]\\ncluster_name = {{serverName}}\\ncluster_description = {{serverDescription}}\\ncluster_password = \\ncluster_intention = cooperative\`
      },
      {
        fileName: 'server.ini',
        fileContent: \`[NETWORK]\\nserver_port = {{serverPort}}\\n[SHARD]\\nis_master = true\\n[STEAM]\\nmaster_server_port = 27018\\nauthentication_port = 8768\`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 3.0GHz+",
    recommendedSsdGB: 10,
    defaultWorldName: 'survival',
  },
};

function generateFiles(config) {
    const gameKey = config.gameName.toLowerCase();
    const gameTemplate = BOT_MOCK_GAME_DATA[gameKey];

    if (!gameTemplate) {
        return null; // Game not found
    }
    
    const recommendedRam = Math.max(gameTemplate.recommendedRamGB, Math.round(config.playerCount / 10 + 2));
    const slugify = (str) => str.toLowerCase().replace(/\\s+/g, '-').replace(/[^a-z0-9-]/g, '');

    const replacements = {
        '{{gameName}}': config.gameName,
        '{{serverName}}': config.serverName,
        '{{serverNameSlug}}': slugify(config.serverName),
        '{{playerCount}}': String(config.playerCount),
        '{{serverPort}}': String(config.serverPort),
        '{{worldSeedOrMap}}': config.worldSeedOrMap || gameTemplate.defaultWorldName,
        '{{serverDescription}}': config.serverDescription,
        '{{recommendedRamGB}}': String(recommendedRam),
    };

    const processTemplate = (templateString) => {
        let result = templateString;
        for (const placeholder in replacements) {
            result = result.replace(new RegExp(placeholder, 'g'), replacements[placeholder]);
        }
        return result;
    };
  
    return {
        explanation: processTemplate(gameTemplate.explanation),
        files: gameTemplate.files.map(file => ({
            fileName: processTemplate(file.fileName),
            fileContent: processTemplate(file.fileContent).trim(),
        }))
    };
};

module.exports = { generateFiles };
`
        },
        {
            fileName: '.env',
            fileContent: `
# Get your Bot Token from the "Bot" page in the Discord Developer Portal
DISCORD_BOT_TOKEN=YOUR_BOT_TOKEN_HERE

# Get your Application ID from the "General Information" page
CLIENT_ID={{discord_client_id}}
`
        },
        {
            fileName: '.gitignore',
            fileContent: `
# Dependencies
/node_modules

# Environment variables
.env

# Logs
logs
*.log
`
        }
    ],
    recommendedRamGB: 1,
    recommendedCpu: "1 Core",
    recommendedSsdGB: 1,
    defaultWorldName: '',
  },
  'valheim': {
    explanation: {
        vi: `Làm theo các bước sau để khởi chạy máy chủ **Valheim** của bạn:\n\n**1. Chuẩn bị:**\n   - Cài đặt **Valheim Dedicated Server** thông qua Steam hoặc SteamCMD.\n\n**2. Tìm thư mục cài đặt:**\n   - Xác định vị trí thư mục gốc nơi máy chủ Valheim của bạn được cài đặt.\n\n**3. Tải về và Đặt tệp:**\n   - Tải tệp \`start_server.sh\` đã tạo và đặt nó vào thư mục gốc đó (cùng chỗ với \`valheim_server.x86_64\`).\n\n**4. Cấp quyền:**\n   - Mở terminal trong thư mục máy chủ và chạy lệnh:\n   \`\`\`\n   chmod +x start_server.sh\n   \`\`\`\n\n**5. Khởi động máy chủ:**\n   - Chạy script bằng lệnh:\n   \`\`\`\n   ./start_server.sh\n   \`\`\`\n\n**QUAN TRỌNG:** Nếu bạn đã đặt mật khẩu, máy chủ của bạn là riêng tư. Nếu không, nó sẽ sử dụng mật khẩu mặc định "secret".`,
        en: `Follow these steps to launch your **Valheim** server:\n\n**1. Prerequisites:**\n   - Install the **Valheim Dedicated Server** via Steam or SteamCMD.\n\n**2. Locate Directory:**\n   - Find the root directory where your Valheim server is installed.\n\n**3. Download & Place File:**\n   - Download the generated \`start_server.sh\` file and place it in that root directory (the same place as \`valheim_server.x86_64\`).\n\n**4. Make Executable:**\n   - Open a terminal in the server directory and run the command:\n   \`\`\`\n   chmod +x start_server.sh\n   \`\`\`\n\n**5. Launch the Server:**\n   - Execute the script with the command:\n   \`\`\`\n   ./start_server.sh\n   \`\`\`\n\n**IMPORTANT:** If you set a password, your server is private. If not, it will use the default "secret" password.`,
    },
    files: [
      {
        fileName: 'start_server.sh',
        fileContent: `
#!/bin/bash
export templdpath=\`dirname \$0\`
export LD_LIBRARY_PATH=\$templdpath/linux64:\$LD_LIBRARY_PATH
export SteamAppId=892970

echo "Starting Valheim server '{{serverName}}'..."

# -nographics: Run in headless mode
# -batchmode: Run in batch mode (no human interaction)
# -name "{{serverName}}": The name of the server
# -port {{serverPort}}: The port for game traffic
# -world "{{worldSeedOrMap}}": The name of the world
# -password "{{valheim_password}}": Server password
# -public 1: 1 for public, 0 for private
./valheim_server.x86_64 -nographics -batchmode -name "{{serverName}}" -port {{serverPort}} -world "{{worldSeedOrMap}}" -password "{{valheim_password}}" -public 1

echo "Valheim server stopped."
`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "4+ Cores @ 3.0GHz+",
    recommendedSsdGB: 10,
    defaultWorldName: 'MyWorld',
  },
  'counter-strike 2': {
    explanation: {
        vi: `Hướng dẫn thiết lập máy chủ **Counter-Strike 2**:\n\n**1. Chuẩn bị:**\n   - Cài đặt **CS2 Dedicated Server** bằng SteamCMD.\n\n**2. Tải về và Sắp xếp tệp:**\n   - Tải tệp \`start.sh\` và đặt nó vào thư mục gốc của máy chủ CS2.\n   - Tạo các thư mục \`csgo/cfg\` bên trong thư mục máy chủ của bạn.\n   - Đặt tệp \`gamemode_casual.cfg\` đã tải vào thư mục \`csgo/cfg\` vừa tạo.\n\n**3. Cấp quyền:**\n   - Mở terminal trong thư mục gốc của máy chủ và chạy lệnh:\n   \`\`\`\n   chmod +x start.sh\n   \`\`\`\n\n**4. Khởi động máy chủ:**\n   - Chạy máy chủ bằng lệnh:\n   \`\`\`\n   ./start.sh\n   \`\`\`\n\n**Tùy chỉnh:** Bạn có thể thay đổi bản đồ mặc định trong \`start.sh\` và điều chỉnh các quy tắc trong \`csgo/cfg/gamemode_casual.cfg\`.`,
        en: `Guide to setting up your **Counter-Strike 2** server:\n\n**1. Prerequisites:**\n   - Install the **CS2 Dedicated Server** using SteamCMD.\n\n**2. Download & Organize Files:**\n   - Download the \`start.sh\` file and place it in the root directory of your CS2 server.\n   - Create the folders \`csgo/cfg\` inside your server directory.\n   - Place the downloaded \`gamemode_casual.cfg\` file into the newly created \`csgo/cfg\` directory.\n\n**3. Make Executable:**\n   - Open a terminal in the server's root directory and run the command:\n   \`\`\`\n   chmod +x start.sh\n   \`\`\`\n\n**4. Launch the Server:**\n   - Run the server using the command:\n   \`\`\`\n   ./start.sh\n   \`\`\`\n\n**Customization:** You can change the default map in \`start.sh\` and adjust game mode rules in the \`csgo/cfg/gamemode_casual.cfg\` file.`,
    },
    files: [
      {
        fileName: 'start.sh',
        fileContent: `
#!/bin/bash
# Startup script for a Counter-Strike 2 Server

echo "Starting CS2 server '{{serverName}}'..."

# Basic command to start a casual server
./cs2 -dedicated +game_type 0 +game_mode 0 +map de_dust2 +sv_lan 0 +hostname "{{serverName}}" +port {{serverPort}}

echo "CS2 server process ended."
`
      },
      {
        fileName: 'csgo/cfg/gamemode_casual.cfg',
        fileContent: `
// CS2 Casual Gamemode Config
// Generated by AI Server Builder

hostname "{{serverName}}"
sv_cheats 0
mp_maxplayers {{playerCount}}
mp_autoteambalance 1
mp_limitteams 1

// Round Timers
mp_roundtime 2.5
mp_freezetime 10

echo "Casual server config loaded for '{{serverName}}'."
`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 3.4GHz+",
    recommendedSsdGB: 40,
    defaultWorldName: 'de_dust2',
  },
  'ark: survival evolved': {
    explanation: {
        vi: `Hướng dẫn thiết lập máy chủ **ARK: Survival Evolved**:\n\n**1. Chuẩn bị:**\n   - Cài đặt máy chủ ARK chuyên dụng bằng SteamCMD.\n\n**2. Tải về và Đặt tệp:**\n   - Tải tệp \`start.sh\` và đặt vào thư mục gốc của máy chủ (\`.../ShooterGame/Binaries/Linux/\`).\n\n**3. Cấp quyền:**\n   - Mở terminal trong thư mục đó và chạy lệnh: \`chmod +x start.sh\`\n\n**4. Khởi động máy chủ:**\n   - Chạy máy chủ với: \`./start.sh\`\n\n**Lưu ý:** Lần khởi động đầu tiên có thể mất nhiều thời gian. Cấu hình chi tiết hơn có thể được thực hiện trong tệp \`.../ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini\`.`,
        en: `Guide to setting up your **ARK: Survival Evolved** server:\n\n**1. Prerequisites:**\n   - Install the ARK dedicated server using SteamCMD.\n\n**2. Download & Place File:**\n   - Download the \`start.sh\` file and place it in your server's root directory (\`.../ShooterGame/Binaries/Linux/\`).\n\n**3. Make Executable:**\n   - Open a terminal in that directory and run: \`chmod +x start.sh\`\n\n**4. Launch the Server:**\n   - Run the server with: \`./start.sh\`\n\n**Note:** The first launch can take a very long time. More detailed configuration can be done in the \`.../ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini\` file.`,
    },
    files: [
      {
        fileName: 'start.sh',
        fileContent: `
#!/bin/bash
# ARK: Survival Evolved startup script

echo "Starting ARK server '{{serverName}}'..."

./ShooterGameServer {{worldSeedOrMap}}?listen?SessionName="{{serverName}}"?MaxPlayers={{playerCount}}?QueryPort=27015?Port={{serverPort}} -server -log
`
      }
    ],
    recommendedRamGB: 8,
    recommendedCpu: "4+ Cores @ 3.4GHz+",
    recommendedSsdGB: 40,
    defaultWorldName: 'TheIsland',
  },
  'terraria': {
    explanation: {
      vi: `Hướng dẫn thiết lập máy chủ **Terraria**:\n\n**1. Chuẩn bị:**\n   - Tải xuống và giải nén tệp máy chủ Terraria từ trang web chính thức.\n\n**2. Tải về và Đặt tệp:**\n   - Tải \`serverconfig.txt\` và \`start.sh\` và đặt chúng vào cùng thư mục với tệp thực thi \`TerrariaServer.bin.x86_64\`.\n\n**3. Cấp quyền:**\n   - Mở terminal và chạy \`chmod +x start.sh\`.\n\n**4. Khởi động:**\n   - Chạy máy chủ bằng lệnh: \`./start.sh\`\n   - Lần đầu tiên, máy chủ sẽ tạo thế giới, quá trình này có thể mất một lúc.`,
      en: `Guide to setting up your **Terraria** server:\n\n**1. Prerequisites:**\n   - Download and unzip the Terraria server files from the official website.\n\n**2. Download & Place Files:**\n   - Download \`serverconfig.txt\` and \`start.sh\` and place them in the same folder as the \`TerrariaServer.bin.x86_64\` executable.\n\n**3. Make Executable:**\n   - Open a terminal and run \`chmod +x start.sh\`.\n\n**4. Launch:**\n   - Run the server with: \`./start.sh\`\n   - The first time, it will generate the world, which may take a moment.`,
    },
    files: [
      {
        fileName: 'serverconfig.txt',
        fileContent: `
#Terraria server config file
worldname={{worldSeedOrMap}}
worldpath=Worlds
maxplayers={{playerCount}}
port={{serverPort}}
motd={{serverName}}
worldsize=2
difficulty=0
`
      },
      {
        fileName: 'start.sh',
        fileContent: `
#!/bin/bash
echo "Starting Terraria server..."
./TerrariaServer.bin.x86_64 -config serverconfig.txt
`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 2.8GHz+",
    recommendedSsdGB: 5,
    defaultWorldName: 'MyTerrariaWorld',
  },
  'left 4 dead 2': {
    explanation: {
      vi: `Hướng dẫn thiết lập máy chủ **Left 4 Dead 2**:\n\n**1. Chuẩn bị:**\n   - Cài đặt máy chủ L4D2 chuyên dụng bằng SteamCMD.\n\n**2. Tải về và Sắp xếp:**\n   - Đặt \`start.sh\` vào thư mục gốc của máy chủ.\n   - Đặt \`server.cfg\` vào thư mục \`left4dead2/cfg/\`.\n\n**3. Cấp quyền:**\n   - Trong terminal, chạy \`chmod +x start.sh\`.\n\n**4. Khởi động:**\n   - Chạy \`./start.sh\` để bắt đầu máy chủ.`,
      en: `Guide to setting up your **Left 4 Dead 2** server:\n\n**1. Prerequisites:**\n   - Install the L4D2 dedicated server using SteamCMD.\n\n**2. Download & Organize:**\n   - Place \`start.sh\` in the server's root directory.\n   - Place \`server.cfg\` in the \`left4dead2/cfg/\` directory.\n\n**3. Make Executable:**\n   - In your terminal, run \`chmod +x start.sh\`.\n\n**4. Launch:**\n   - Run \`./start.sh\` to start the server.`,
    },
    files: [
      {
        fileName: 'start.sh',
        fileContent: `
#!/bin/bash
# Left 4 Dead 2 startup script
./srcds_run -game left4dead2 +exec server.cfg +map c1m1_hotel +port {{serverPort}}
`
      },
      {
        fileName: 'left4dead2/cfg/server.cfg',
        fileContent: `
hostname "{{serverName}}"
sv_maxplayers {{playerCount}}
sv_cheats 0
sv_lan 0
`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 3.0GHz+",
    recommendedSsdGB: 15,
    defaultWorldName: 'c1m1_hotel',
  },
  'palworld': {
    explanation: {
      vi: `Hướng dẫn thiết lập máy chủ **Palworld**:\n\n**1. Chuẩn bị:**\n   - Cài đặt máy chủ Palworld chuyên dụng bằng SteamCMD.\n\n**2. Tải về và Đặt tệp:**\n   - Tải tệp \`start.sh\` và đặt nó vào thư mục gốc của máy chủ Palworld.\n\n**3. Cấu hình:**\n   - Chạy máy chủ một lần để tạo tệp \`PalWorldSettings.ini\`. Sau đó, dừng máy chủ.\n   - Sao chép \`DefaultPalWorldSettings.ini\` vào \`Pal/Saved/Config/LinuxServer/PalWorldSettings.ini\` và chỉnh sửa các cài đặt như \`ServerName\`, \`ServerDescription\`, v.v. để khớp với yêu cầu của bạn. Cổng máy chủ nên được đặt thành \`{{serverPort}}\` trong tệp này (\`PublicPort\`).\n\n**4. Cấp quyền và Khởi động:**\n   - Chạy \`chmod +x start.sh\` và sau đó \`./start.sh\` để khởi động máy chủ của bạn.`,
      en: `Guide to setting up your **Palworld** server:\n\n**1. Prerequisites:**\n   - Install the Palworld dedicated server using SteamCMD.\n\n**2. Download & Place File:**\n   - Download the \`start.sh\` file and place it in your Palworld server root directory.\n\n**3. Configuration:**\n   - Run the server once to generate the \`PalWorldSettings.ini\` file. Then stop it.\n   - Copy \`DefaultPalWorldSettings.ini\` to \`Pal/Saved/Config/LinuxServer/PalWorldSettings.ini\` and edit settings like \`ServerName\`, \`ServerDescription\`, etc. to match your request. The port should be set to \`{{serverPort}}\` in this file (\`PublicPort\`).\n\n**4. Make Executable & Launch:**\n   - Run \`chmod +x start.sh\` and then \`./start.sh\` to launch your server.`,
    },
    files: [
      {
        fileName: 'start.sh',
        fileContent: `
#!/bin/bash
echo "Starting Palworld Server..."
# The server name and other settings are configured in PalWorldSettings.ini
./PalServer.sh -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
`
      }
    ],
    recommendedRamGB: 8,
    recommendedCpu: "4+ Cores @ 3.5GHz+",
    recommendedSsdGB: 30,
    defaultWorldName: 'Default',
  },
  'factorio': {
    explanation: {
      vi: `Hướng dẫn thiết lập máy chủ **Factorio**:\n\n**1. Chuẩn bị:**\n   - Tải xuống phiên bản headless của Factorio từ trang web chính thức.\n\n**2. Tạo Lưu trữ:**\n   - Lần đầu tiên, tạo một bản lưu bằng lệnh: \`./bin/x64/factorio --create {{worldSeedOrMap}}.zip\`\n\n**3. Tải về và Đặt tệp:**\n   - Tải \`start.sh\` và \`server-settings.json\` và đặt chúng vào thư mục gốc của máy chủ Factorio.\n\n**4. Cấp quyền và Khởi động:**\n   - Chạy \`chmod +x start.sh\` và sau đó \`./start.sh\` để khởi động máy chủ.`,
      en: `Guide to setting up your **Factorio** server:\n\n**1. Prerequisites:**\n   - Download the headless version of Factorio from the official website.\n\n**2. Create Save:**\n   - For the first time, create a save with: \`./bin/x64/factorio --create {{worldSeedOrMap}}.zip\`\n\n**3. Download & Place Files:**\n   - Download \`start.sh\` and \`server-settings.json\` and place them in the Factorio root directory.\n\n**4. Make Executable & Launch:**\n   - Run \`chmod +x start.sh\` and then \`./start.sh\` to launch the server.`,
    },
    files: [
      {
        fileName: 'start.sh',
        fileContent: `
#!/bin/bash
./bin/x64/factorio --start-server {{worldSeedOrMap}}.zip --server-settings ./server-settings.json --port {{serverPort}}
`
      },
      {
        fileName: 'server-settings.json',
        fileContent: `
{
  "name": "{{serverName}}",
  "description": "{{serverDescription}}",
  "tags": ["game", "factorio"],
  "max_players": {{playerCount}},
  "visibility": {
    "public": true
  },
  "game_password": "",
  "auto_pause": true
}
`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 3.0GHz+",
    recommendedSsdGB: 5,
    defaultWorldName: 'factorio-save',
  },
  'project zomboid': {
    explanation: {
      vi: `Hướng dẫn thiết lập máy chủ **Project Zomboid**:\n\n**1. Chuẩn bị:**\n   - Cài đặt máy chủ Project Zomboid chuyên dụng bằng SteamCMD.\n\n**2. Tải về và Đặt tệp:**\n   - Tải \`start-server.sh\` đã tạo và đặt nó vào thư mục gốc của máy chủ, ghi đè lên tệp hiện có.\n\n**3. Cấu hình:**\n   - Máy chủ được cấu hình thông qua các tệp \`.ini\` trong \`~/Zomboid/Server/\`. Lệnh khởi động chỉ đặt tên máy chủ. Chỉnh sửa \`ServerTest.ini\` để thay đổi số lượng người chơi, cổng máy chủ (\`DefaultPort\`), và các cài đặt khác.\n\n**4. Khởi động:**\n   - Chạy \`./start-server.sh\` để bắt đầu.`,
      en: `Guide to setting up your **Project Zomboid** server:\n\n**1. Prerequisites:**\n   - Install the Project Zomboid dedicated server using SteamCMD.\n\n**2. Download & Place File:**\n   - Download the generated \`start-server.sh\` and place it in your server's root directory, overwriting the existing one.\n\n**3. Configuration:**\n   - The server is configured via \`.ini\` files in \`~/Zomboid/Server/\`. The start command only sets the server name. Edit \`ServerTest.ini\` to change player count, server port (\`DefaultPort\`), and other settings.\n\n**4. Launch:**\n   - Run \`./start-server.sh\` to begin.`,
    },
    files: [
      {
        fileName: 'start-server.sh',
        fileContent: `#!/bin/bash
DIR="$( cd "$( dirname "\\\${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# This script is a wrapper. Server settings are primarily in the .ini files.
"$DIR/jre64/bin/java" -Xmx{{recommendedRamGB}}g -jar "$DIR/server.jar" -servername "{{serverName}}"`
      }
    ],
    recommendedRamGB: 6,
    recommendedCpu: "4+ Cores @ 3.0GHz+",
    recommendedSsdGB: 15,
    defaultWorldName: 'Muldraugh, KY',
  },
  "don't starve together": {
    explanation: {
      vi: `Thiết lập máy chủ **Don't Starve Together** phức tạp:\n\n**1. Chuẩn bị:**\n   - Cài đặt máy chủ DST chuyên dụng bằng SteamCMD.\n\n**2. Cấu trúc thư mục:**\n   - Tạo một thư mục cluster, ví dụ: \`~/.klei/DoNotStarveTogether/MyDSTServer\`. Đặt tệp \`cluster.ini\` đã tạo vào đó.\n   - Tạo một thư mục con \`Master\` bên trong \`MyDSTServer\` và đặt tệp \`server.ini\` vào đó.\n\n**3. Token Cluster:**\n   - Bạn phải tạo một token cluster trong game và thêm nó vào \`cluster.ini\`.\n\n**4. Khởi động:**\n   - Chạy máy chủ từ thư mục \`bin\` của DST: \`./dontstarve_dedicated_server_nullrenderer -cluster MyDSTServer -shard Master\``,
      en: `Setting up a **Don't Starve Together** server is complex:\n\n**1. Prerequisites:**\n   - Install the DST dedicated server using SteamCMD.\n\n**2. Directory Structure:**\n   - Create a cluster directory, e.g., \`~/.klei/DoNotStarveTogether/MyDSTServer\`. Place the generated \`cluster.ini\` there.\n   - Create a \`Master\` subdirectory inside \`MyDSTServer\` and place \`server.ini\` inside it.\n\n**3. Cluster Token:**\n   - You must generate a cluster token in-game and add it to your \`cluster.ini\`.\n\n**4. Launch:**\n   - Run the server from the DST \`bin\` directory: \`./dontstarve_dedicated_server_nullrenderer -cluster MyDSTServer -shard Master\``,
    },
    files: [
      {
        fileName: 'cluster.ini',
        fileContent: `
[GAMEPLAY]
game_mode = survival
max_players = {{playerCount}}
pvp = false
pause_when_empty = true

[NETWORK]
cluster_name = {{serverName}}
cluster_description = {{serverDescription}}
cluster_password = 
cluster_intention = cooperative
`
      },
      {
        fileName: 'server.ini',
        fileContent: `
[NETWORK]
server_port = {{serverPort}}

[SHARD]
is_master = true

[STEAM]
master_server_port = 27018
authentication_port = 8768
`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 3.0GHz+",
    recommendedSsdGB: 10,
    defaultWorldName: 'survival',
  },
};
