
import type { GeneratedConfig } from '../types';

type MockExplanation = {
  vi: string;
  en: string;
}

// A template for a generated config. The final values will be computed.
interface MockConfigTemplate {
  explanation: MockExplanation;
  files: {
    fileName: string;
    fileContent: string;
  }[];
  recommendedRamGB: number;
  recommendedCpu: string;
  recommendedSsdGB: number;
  defaultWorldName: string;
}

// Using a Record for strong typing. Keys should be lowercase game names.
export const MOCK_GAME_DATA: Record<string, MockConfigTemplate> = {
  'minecraft': {
    explanation: {
      vi: `Đây là hướng dẫn chi tiết để thiết lập máy chủ **Minecraft** của bạn:\n\n**1. Chuẩn bị:**\n   - Đảm bảo bạn đã cài đặt **Java 17** trở lên.\n   - Tải tệp \`server.jar\` từ trang chủ chính thức của Minecraft.\n\n**2. Tạo thư mục máy chủ:**\n   - Tạo một thư mục mới, trống cho máy chủ của bạn (ví dụ: \`minecraft-server\`).\n\n**3. Tải về và Sắp xếp tệp:**\n   - Tải các tệp đã tạo (\`server.properties\`, \`start.sh\`, \`eula.txt\`) và đặt chúng vào thư mục \`minecraft-server\` cùng với tệp \`server.jar\`.\n\n**4. Cấp quyền (Linux/macOS):**\n   - Mở terminal, điều hướng đến thư mục máy chủ và chạy lệnh sau:\n   \`\`\`\n   chmod +x start.sh\n   \`\`\`\n\n**5. Khởi động máy chủ:**\n   - Chạy lệnh sau trong terminal:\n   \`\`\`\n   ./start.sh\n   \`\`\`\n   - Lần khởi động đầu tiên sẽ mất một lúc để tạo thế giới. Máy chủ của bạn hiện đã hoạt động!`,
      en: `Here is a detailed guide to set up your **Minecraft** server:\n\n**1. Prerequisites:**\n   - Make sure you have **Java 17** or newer installed.\n   - Download the \`server.jar\` file from the official Minecraft website.\n\n**2. Create Server Folder:**\n   - Create a new, empty folder for your server (e.g., \`minecraft-server\`).\n\n**3. Download & Place Files:**\n   - Download the generated files (\`server.properties\`, \`start.sh\`, \`eula.txt\`) and place them inside the \`minecraft-server\` folder, alongside your \`server.jar\` file.\n\n**4. Make Executable (Linux/macOS):**\n   - Open your terminal, navigate to the server folder, and run the command:\n   \`\`\`\n   chmod +x start.sh\n   \`\`\`\n\n**5. Launch the Server:**\n   - Run the following command in your terminal:\n   \`\`\`\n   ./start.sh\n   \`\`\`\n   - The first launch will take a moment to generate the world. Your server is now live!`,
    },
    files: [
      {
        fileName: 'server.properties',
        fileContent: `
#Minecraft server properties
#Generated by AI Server Builder
motd={{serverName}}
server-port=25565
max-players={{playerCount}}
level-seed={{worldSeedOrMap}}
gamemode=survival
difficulty=easy
pvp=true
enforce-whitelist=false
view-distance=10
`
      },
      {
        fileName: 'start.sh',
        fileContent: `
#!/bin/bash
# A simple startup script for a Minecraft Server
# Make sure to have 'server.jar' in the same directory.

echo "Starting Minecraft server '{{serverName}}'..."
java -Xmx{{recommendedRamGB}}G -Xms1G -jar server.jar nogui
`
      },
      {
        fileName: 'eula.txt',
        fileContent: `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).\neula=true`
      }
    ],
    recommendedRamGB: 6,
    recommendedCpu: "4+ Cores @ 3.2GHz+",
    recommendedSsdGB: 20,
    defaultWorldName: 'world',
  },
  'valheim': {
    explanation: {
        vi: `Làm theo các bước sau để khởi chạy máy chủ **Valheim** của bạn:\n\n**1. Chuẩn bị:**\n   - Cài đặt **Valheim Dedicated Server** thông qua Steam hoặc SteamCMD.\n\n**2. Tìm thư mục cài đặt:**\n   - Xác định vị trí thư mục gốc nơi máy chủ Valheim của bạn được cài đặt.\n\n**3. Tải về và Đặt tệp:**\n   - Tải tệp \`start_server.sh\` đã tạo và đặt nó vào thư mục gốc đó (cùng chỗ với \`valheim_server.x86_64\`).\n\n**4. Cấp quyền:**\n   - Mở terminal trong thư mục máy chủ và chạy lệnh:\n   \`\`\`\n   chmod +x start_server.sh\n   \`\`\`\n\n**5. Khởi động máy chủ:**\n   - Chạy script bằng lệnh:\n   \`\`\`\n   ./start_server.sh\n   \`\`\`\n\n**QUAN TRỌNG:** Mở tệp \`start_server.sh\` và **thay đổi mật khẩu mặc định** "secret" thành một mật khẩu an toàn!`,
        en: `Follow these steps to launch your **Valheim** server:\n\n**1. Prerequisites:**\n   - Install the **Valheim Dedicated Server** via Steam or SteamCMD.\n\n**2. Locate Directory:**\n   - Find the root directory where your Valheim server is installed.\n\n**3. Download & Place File:**\n   - Download the generated \`start_server.sh\` file and place it in that root directory (the same place as \`valheim_server.x86_64\`).\n\n**4. Make Executable:**\n   - Open a terminal in the server directory and run the command:\n   \`\`\`\n   chmod +x start_server.sh\n   \`\`\`\n\n**5. Launch the Server:**\n   - Execute the script with the command:\n   \`\`\`\n   ./start_server.sh\n   \`\`\`\n\n**IMPORTANT:** Edit the \`start_server.sh\` file and **change the default password** from "secret" to something secure!`,
    },
    files: [
      {
        fileName: 'start_server.sh',
        fileContent: `
#!/bin/bash
export templdpath=\`dirname \$0\`
export LD_LIBRARY_PATH=\$templdpath/linux64:\$LD_LIBRARY_PATH
export SteamAppId=892970

echo "Starting Valheim server '{{serverName}}'..."

# -nographics: Run in headless mode
# -batchmode: Run in batch mode (no human interaction)
# -name "{{serverName}}": The name of the server
# -port 2456: The port for game traffic
# -world "{{worldSeedOrMap}}": The name of the world
# -password "secret": CHANGE THIS PASSWORD!
# -public 1: 1 for public, 0 for private
./valheim_server.x86_64 -nographics -batchmode -name "{{serverName}}" -port 2456 -world "{{worldSeedOrMap}}" -password "secret" -public 1

echo "Valheim server stopped."
`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "4+ Cores @ 3.0GHz+",
    recommendedSsdGB: 10,
    defaultWorldName: 'MyWorld',
  },
    'counter-strike 2': {
    explanation: {
        vi: `Hướng dẫn thiết lập máy chủ **Counter-Strike 2**:\n\n**1. Chuẩn bị:**\n   - Cài đặt **CS2 Dedicated Server** bằng SteamCMD.\n\n**2. Tải về và Sắp xếp tệp:**\n   - Tải tệp \`start.sh\` và đặt nó vào thư mục gốc của máy chủ CS2.\n   - Tạo các thư mục \`csgo/cfg\` bên trong thư mục máy chủ của bạn.\n   - Đặt tệp \`gamemode_casual.cfg\` đã tải vào thư mục \`csgo/cfg\` vừa tạo.\n\n**3. Cấp quyền:**\n   - Mở terminal trong thư mục gốc của máy chủ và chạy lệnh:\n   \`\`\`\n   chmod +x start.sh\n   \`\`\`\n\n**4. Khởi động máy chủ:**\n   - Chạy máy chủ bằng lệnh:\n   \`\`\`\n   ./start.sh\n   \`\`\`\n\n**Tùy chỉnh:** Bạn có thể thay đổi bản đồ mặc định trong \`start.sh\` và điều chỉnh các quy tắc trong \`csgo/cfg/gamemode_casual.cfg\`.`,
        en: `Guide to setting up your **Counter-Strike 2** server:\n\n**1. Prerequisites:**\n   - Install the **CS2 Dedicated Server** using SteamCMD.\n\n**2. Download & Organize Files:**\n   - Download the \`start.sh\` file and place it in the root directory of your CS2 server.\n   - Create the folders \`csgo/cfg\` inside your server directory.\n   - Place the downloaded \`gamemode_casual.cfg\` file into the newly created \`csgo/cfg\` directory.\n\n**3. Make Executable:**\n   - Open a terminal in the server's root directory and run the command:\n   \`\`\`\n   chmod +x start.sh\n   \`\`\`\n\n**4. Launch the Server:**\n   - Run the server using the command:\n   \`\`\`\n   ./start.sh\n   \`\`\`\n\n**Customization:** You can change the default map in \`start.sh\` and adjust game mode rules in the \`csgo/cfg/gamemode_casual.cfg\` file.`,
    },
    files: [
      {
        fileName: 'start.sh',
        fileContent: `
#!/bin/bash
# Startup script for a Counter-Strike 2 Server

echo "Starting CS2 server '{{serverName}}'..."

# Basic command to start a casual server
./cs2 -dedicated +game_type 0 +game_mode 0 +map de_dust2 +sv_lan 0 +hostname "{{serverName}}"

echo "CS2 server process ended."
`
      },
      {
        fileName: 'csgo/cfg/gamemode_casual.cfg',
        fileContent: `
// CS2 Casual Gamemode Config
// Generated by AI Server Builder

hostname "{{serverName}}"
sv_cheats 0
mp_maxplayers {{playerCount}}
mp_autoteambalance 1
mp_limitteams 1

// Round Timers
mp_roundtime 2.5
mp_freezetime 10

echo "Casual server config loaded for '{{serverName}}'."
`
      }
    ],
    recommendedRamGB: 4,
    recommendedCpu: "2+ Cores @ 3.4GHz+",
    recommendedSsdGB: 40,
    defaultWorldName: 'de_dust2',
  },
};
